### ISSUE TITLE
Some tsv files referenced using `Links` hold multiple types

### ISSUE THREAD

**Issue by prashantbarca** [pdf-association/arlington-pdf-model#10]
The following files can be referenced as both an array and a name-tree. Most of them are all referenced from the Name dictionary, except the last one. 

1. DestXYZ, Dest0, Dest1, and Dest4 from the Dests field.
2. ActionECMAScript from the Javascripts field.
3. FileSpecification from the EmbeddedFiles field.
4. ArrayOfStructElem referenced in StructTreeRoot line 5 as a number tree. 

Similarly, 

1. 3DView is usually a dictionary, but it is referred to as an array in 3DStream. 
2. VisibilityExpressionArray gets referred to as a dictionary in the * row of VisibilityExpressionArray, whereas it is normally an array (with 0, 1, *). 

This is problematic because the arrays usually hold indices 0-n or * as the key value, whereas name-trees hold dictionary keys. We need to create a separate type with the correct entries for the name-tree or dictionary type when appropriate. 

Finally, it seems like the _UniversalDictionary type is defined as an array in XObjectFormTrapNet: row 30.

**Comment by petervwyatt** [comment]
Referencing links as both an `array` and `name-/number-tree` is valid in the Arlington model, since ISO 32000-2:2020 clause 7.9.6 Name trees says "The values associated with the keys may be objects of any type." - and this also applies to Number trees.

I have updated the TestGrammar PoC to detect when TSV array definitions are referenced as dicts or streams and vice-versa. This found a few other mistakes in other PDF objects (incl. 3DView, VisibilityExpressionArray and XObjectFormTrapNet). So I believe I have fixed everything with the latest commit you identified.

Note that this does result in an ambiguity in the Arlington TSV syntax, since a TSV definition with a just single wildcard row `*` could be either an array of arbitrary length OR a dict with arbitrary key names. This can only be resolved by the referring context (aka Link) and if that Link is a name- or number-tree then it is totally ambiguous. The only solution I can think of for this is to create a new predicate, possibly on the Type value to disambiguate for the trees: e.g. `fn:Tree(number-tree, dictionary)`,  `fn:Tree(name-tree, array)`, etc. 

However I am yet to find such a situation so this is food for thought for the future...
