### ISSUE TITLE
EncryptionPublicKey CF must be CryptFilterPublicKeyMap

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#110]
The CF key is defined as  `[CryptFilterMap,CryptFilterPublicKeyMap]`, but this can only be `CryptFilterPublicKeyMap`, surely?

I have sample files if you need them, but they are encrypted (you may have guessed that already :-). But if I change that definition in our implementation here, it removes the Arlington warning we produce due to it matching a `CryptFilterMap`

**Comment by petervwyatt** [comment]
"Table 20 — Entries common to all encryption dictionaries" defines **CF** and is for "_all encryption dicts_" and goes on to describe how it is a map. Although it says "_Every crypt filter used in the document shall have an entry in this dictionary", it doesn't say "only" so it can, theoretically / syntactically, contain other unnecessary entries including the predefined **Identity** and **StdCF**. That is why `CryptFilterMap.tsv` is included since the PDF spec defines precisely what those entries should look like - and Arlington models what is allowed, not what is sensible 😀.

The way that Arlington is defined is that the order of "Links" references are not significant (I know my C++ PoC implementation can cause false warnings because of this). I assume the issue for you is that the wildcard in `CryptFilterMap.tsv` matches before the wildcard in `CryptFilterPublicKeyMap.tsv`?

**Comment by faceless2** [comment]
No problem - on first glance it looked like an oversight, but if it's supposed to be that way... yes, we generally pick up the first item on the list that matches, but have a few excptions where we look deeper first. Another exception coming up! Thanks Peter.
