### ISSUE TITLE
Permissions DocMDP field has wrong value.

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#20]
`Permissions.tsv` field `DocMDP` refers to `SignatureReferenceDocMDP`. But I think it should refer to a `Signature` that contains a `Reference` array that contains a `SignatureReferenceDocMDP`

Here's a demonstrator: [Sign-bad.pdf](https://github.com/pdf-association/arlington-pdf-model/files/9645784/Sign-bad.pdf)

(we're now incorporating this, reimplementing from the spec. So apologies in advance, because there are going to be a few issues raised and some of them will certainly be my error!)

**Comment by petervwyatt** [comment]
Table 29 Catalog **Perms** explicitly references subclause "12.8.6 Permissions". `Permissions.tsv` thus represents "Table 263 — Entries in a permissions dictionary"

**DocMDP** entry is defined as "An indirect reference to a signature dictionary (see "Table 255 — Entries in a signature dictionary")"
PS. I have now also fixed the IndirectReference to be TRUE in `Permissions.tsv` on the GitHub "Extensions" branch.

So you are correct that `SignatureReferenceDocMDP.tsv` is incorrect - it should be linking to `Signature.tsv`.
PS. I have fixed Permissions.tsv on the GitHub "Extensions" branch.

"Table 263 — Entries in a permissions dictionary" also says "_This dictionary shall contain a **Reference** entry that shall be a signature reference dictionary (see "Table 255 — Entries in a signature dictionary") that has a **DocMDP** transform method (see 12.8.2.2, "DocMDP") and corresponding transform parameters._" so I added a new predicate check for this to `Permissions.tsv` as a SpecialCase: `[fn:Eval(fn:ArrayLength(DocMDP::Reference)>=1)]` (avoid validating for an empty array).

PS. technically "_This dictionary shall contain a **Reference** entry that shall be a signature reference dictionary..._" is an incorrect statement since Reference is always an array. It should say "This dictionary shall contain a **Reference** entry that shall be an array with an entry that is a signature reference dictionary...". See https://github.com/pdf-association/pdf-issues/issues/218 if you'd like to contribute improved wording or if you know the rules related to multiple array entries...

Thanks for the contribution!
PPS. Please switch to the GitHub "Extensions" branch as it has many other data model improvements.

**Comment by petervwyatt** [comment]
Fixed on "Extensions" branch
