### ISSUE TITLE
No indications for the removal of XObjectFormPS & XObjectFormPSpassthrough

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/arlington-pdf-model#3]
The PostScript XObject has been removed and not included in ISO 32000-2. It seems there's no indications for this removal?
The `XObjectMap.tsv` is this:
```text
*	stream	1.0		FALSE	TRUE	FALSE				[XObjectFormType1,XObjectImage,fn:SinceVersion(1.1,XObjectFormPS),fn:SinceVersion(1.1,XObjectFormPSpassthrough)]	
```
and it said nothing about the removal.

Also maybe it worth expressing the PDF 1.x "PostScript XObjects should not be used" recommendation somehow (not sure why it wasn't deprecated at the time).

**Comment by petervwyatt** [comment]
The way I encoded the deprecation (or, more correctly, its removal from the Adobe PDF reference) was that every key in both XObjectFormPS.tsv and XObjectFormPSpassthrough.tsv has the "DeprecatedIn" field set to PDF 1.3.

I do appreciate that this is syntactically different to the way I encode introduction of a new object type ("fn:SinceVersion(1.1,xxx)"). At one point I tried using nested predicates ("fn:Deprecated(1.3, fn:SinceVersion(1.1,xxx))") but that is slightly more difficult to parse. If you feel otherwise, or think that is a clearer syntax please let me know.

Thanks for your contributions!
