### ISSUE TITLE
Grammar typing

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#30]
I've hit something I can't figure out.

In `FilterFlateDecode` you have this test in possible value for `Colors`, which must be between 1 and 4 prior to PDF 1.3, otherwise greater than 1.
```
fn:Eval((@Colors>=1) && fn:BeforeVersion(1.3,fn:Eval(@Colors<=4)))
```

I'm assuming each function outputs a PDF value -  _true_, _false_, _null_, or a name, string, number or array - and when I evaluate any of those as a boolean, anything other than _false_ or _null_ is treated as _true_. So as this file is version 1.6, I'm returning _null_, which in a boolean context is _false_. But that's incorrect - it means it's always false.

The text for fn:Before says the expression "only applies before _version_". So if version is 1.6, it "does not apply".

How does "does not apply" fit into a boolean logic? Ignore it? So all these are the same?

```
fn:Eval((@Colors>=1) && fn:BeforeVersion(1.3,fn:Eval(@Colors<=4)))
fn:Eval((@Colors>=1) || fn:BeforeVersion(1.3,fn:Eval(@Colors<=4)))
fn:Eval((@Colors>=1) && fn:Not(fn:BeforeVersion(1.3,fn:Eval(@Colors<=4))))
```

I had a whole pile of questions on the type system but eventually felt I'd figured it out, but this one has me convinced I've misunderstood something pretty fundamental. Unless it's a bug. Please say it's a bug, I don't want to find I have to redo everything with ternary logic 😄 

Here's the model I've been using - essentially the one for most loosely-typed languages.

* functions returns types equivalent to primitive PDF types, including null, or arrays
* typing is loose - a default value of `1.2` is a name if the field is a name, a number otherwise.
* when evaluating in a boolean context, _false_ and _null_ are false, everything else is true.
* `a || b` is `a` if `a` is not _false_ or _null_, `b` otherwise. (eg `fn:Eval(fn:DefaultValue(@StateModel=='Marked','Unmarked') || fn:DefaultValue(@StateModel=='Review','None'))`)
* `a && b` is _true_ if both `a` and `b` are not _false_ or _null_, _false_ otherwise.

**Comment by petervwyatt** [comment]
Yes, no, and things are still evolving 😁. 

* Yes, things are declared in the Arlington grammar as loosely typed as you state (so things need to match or be interpreted as matching the "Type" field). This is where Python is a PITA as we have keys called things like "/1.2" which is encoded into Arlington as "1.2" as a name, not a number! But the result of evaluating a predicate is getting more complex (esp. for multi-valued things like PDF arrays or name/number trees, since the predicate may not know the exact array index - but I still use a `@arraykey` syntax 

* But sorry no for the boolean logic, as it's not quite that simple (I originally thought it would be but things "got complicated" as they say!) - and it is still a little fluid...

I have some comments here that explain some details: https://github.com/pdf-association/arlington-pdf-model/blob/extensions/TestGrammar/src/PDFFile.cpp#L277

but as of earlier this week, things got more complicated because of supporting custom named extensions in the "SinceVersion" field (for which I am yet to update the doco).  See `cut -f 3 * | sort | uniq` - a logical expression in the "SinceVersion" field like `fn:Eval(fn:Extension(ADBE_Extn3,1.7) || 2.0)` resolves down to a PDF version... so this is interpreted more as natural language rather than formal Boolean logic. Bitmasks are another.

The key goal has always been to make the internal grammar as easy to read for a human (from left-to-right), even if it makes processing easier. I often read aloud the predicate expression to see if it makes sense...

Always happy for suggestions on improvements or clarifications to the internal grammar, but definitely want to steer clear of a "programming language" style. Early considerations included possibly using LUA or JS instead of declarative predicates but extremely glad we didn't go down that path for various reasons...

**Comment by faceless2** [comment]
OK, that's not too bad. Thanks for the pointer to the code - I've been trying to work from the spec alone, but the code offers insight and is very easy to follow (I don't get to say that too often). It answered a lot of questions.

We effectively have a three-valued logic - there's an `undefined` value which you're representing with a C NULL (distinct from a PDF `null`):
```
a || undefined == undefined || a == a
a && undefined == undefined && a == a
fn:Not(undefined) = undefined
(a == undefined) == undefined
(a != undefined) == undefined
(a * undefined) == undefined (same for all other operators)
```
Personally I think it should be `(a==undefined)==false` and `(a!=undefined)==true` - that would let you clean up the tautological horror that is `fn:Not(fn:IsPresent(@ImageMask==true))`. But I can live with it.

Now these concept are clear, we've finished the special-case rules and have a full implementation at last. Seems to work too - things that are valid (eg ISO32K spec) are.

In terms of what could improve - well, I think the typing discussion we just had would help in the reference.

I found three areas particularly confusing:

* the section on predicate types - we have `expr` which claims to be "mathematical", `cond` which claims to be boolean and `statement`. But they're all the same thing - it's not like one can use multiplication and one can't. What differs is how the result of evaluation is used. The definitions in this section don't really match what's used in each function (`cond` vs `condition`, `key` is not defined, etc) so it might need a bit of a polish.
* a _path_ structure sometimes needs an '@':`fn:Eval(@a==1)`, and sometimes doesn't: `fn:IsPresent(a)`. I understand that the `@` distinguishes a name from a path, and I believe that's all it's for: if the name-like thing you have in front of you has an `@` on the _final path segment_, strip it out and parse it as a path. I can see assertions preventing `fn:IsPresent(@a)`, but it seems pretty arbitrary. I also think that where you have `key` it can technically be _any_ path, including `parent::` or `trailer::`, rather than just a key in this current object. In which case I'd suggest renaming key to path to make this clear.
* finally it would have helped me if the function descriptions where a bit more prescriptive - for example `fn:BeforeVersion` says "_assertion is a fn:Eval(...) expression that only applies before version._", whereas looking at the code I can see it's more like "_If a statement is supplied, the return value is the statement if the version condition is met, undefined otherwise. If no statement is supplied the return value is true if the version condition is met, false otherwise_". Assuming this "undefined" concept is the right one, but you get the idea.

Some other nitpicks:

* fn:ArrayLength, StringLength, StreamLength say they return -1 if the value is missing - no, they returns undefined. How else can `fn:Eval(fn:ArrayLength(DecodeParms)==fn:ArrayLength(Filter))` work if there's no DecodeParms set!
* fn:StreamLength and fn:RectWidth "need to be wrapped inside fn:Eval" but fn:ArrayLength does not? Don't think that sentence is required anymore. It's on a few other predicates as well
* might be useful to note that `fn:IsPresent()` does not take into account default values.

Lastly a concept I think might help the grammar:

* how about a pointer to the current object we can use in expressions? There's a whole category of special-case tests this might help - perhaps `@` to mean this object, for things like `fn:Eval(Next::@Prev==@)`

But overall it works, I managed to get 95% of the way there with just the spec and your copious assistance :-)

**Comment by petervwyatt** [comment]
I have hopefully now addressed all your points in the last comment, subject to further human error:

* INTERNAL_GRAMMAR.md has been updated and the definitions for `expr`, `statement`, etc. removed. My thinking and the data model have both evolved since I wrote this so good pick up...

* re the use of `@` - just reading aloud should help you know if you need the `@` as it is verbalised as "_the value of the key..._". Thus you should never be able to do any math operation without a `@`. It is an important semantic detail as 32K is very careful with wording between "key", "value" and "entry" as each has a **very specific** meaning. I've updated INTERNAL_GRAMMAR.md, checked all `@` and I don't think there are any remaining errors. 

* I have significantly reworked all the definitions for all predicates in INTERNAL_GRAMMAR.md to stay well away from any implementation details. It is now all (and only) about assertions of facts.

* `fn:IsPresent` and default values is interesting - arguably this would be a glitch in the PDF spec possibly caused by a change of required/optional-ness over time and some dependence wording elsewhere that wasn't maintained in parallel. But this would only apply to the use of `fn:IsPresent` in the "Required" field. Default value processing is still needed for "SpecialCase" evaluation as there were a few false warnings caused by by missing keys that rely on a default value.

* because of predicate logic, trying to stay close to first order logic, logic programming, etc. we do not want to introduce the concept of variables or any other functional programming idiom. That also reduces the viability to use the model in something like Jupyter Notebooks or Linux CLI voodoo where extracted fields need to "stand alone" and not be contextualized. An early iteration of the model used this syntax and it made model queries almost impossible to do easily (th model is not just about file validation). Hence exploit is always best - and is the LangSec way!

**Comment by petervwyatt** [comment]
`fn:IsPresent` implementation in C++ TestGrammar PoC now only processes DefaultValue for SpecialCase predicates.
If you see a new warning or error, then there is either an issue in the spec or the model definition.
(I forgot to tag this issue on commit!)
