### ISSUE TITLE
Combination of SpecialCase and Required on missing fields is odd.

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#33]
`XObjectImage` table, the `ColorSpace` has this for type:

```
type
  array;name

required
  fn:IsRequired(fn:Not(fn:Contains(@Filter,JPXDecode)))

specialcase
  [fn:Not(fn:IsPresent(@ImageMask==true))];[fn:Not(fn:IsPresent(@ImageMask==true))]
```

... with the intent that ColorSpace is not required if the filter is JPXDecode, and the ColorSpace is not allowed if the ImageMask is set

So consider a regular, non JPX image with `/ImageMask true`: the Filter is not JPXDecode, so the `ColorSpace` is required. Clearly that's not the case, so I presume the idea is that I'm also supposed to check the Special-Case column too, even if the field is missing: if it's false, the ColorSpace would have been disallowed, so can't be required.

The problem is that because the ColorSpace is missing, I don't know which type it is, so I don't know which of the two SpecialCase predicates I'm supposed to check. In this example they're both the same, but what if special-case were `[FALSE];[TRUE]`?

I'm can make progress by assuming it's the first type if it's missing, but this feels a bit wrong. It might be worth noting in the grammar guide, or alternatively the fn:IsRequired test could be altered.

**Comment by petervwyatt** [comment]
You stumbled across some of the first predicates we tried... and we were undecided then about if the Required field should have predicates or not.

The Arlington "Required" field only reflects when a key is required or if it is optional - it does not try to capture any "prohibited" case - it is effectively a boolean. Prohibiting conditions are encoded in the SpecialCase field. Of course, prohibited keys cannot also be Required (it must be optional) - this would be a data entry error in the Arlington data model. This structure is representative of how the PDF spec has historically been written (mostly) - where prohibition rules are often expressed in freeform prose but the required/optional is always stated in a standard manner in the italicised text at the start of the description cell.

So in this case an ImageMask condition needs to be added to the Required field so it then calculates as being optional.
The SpecialCase predicate is then kept as-is, since it is expressing the prohibition rule on the now optional key.

Interestingly, the wording for **BitsPerComponent** in Table 87 is a more succinct and clearer "_(Required except for image masks and images that use the JPXDecode filter)_" followed by additional details in the prose. 

If the model wasn't trying to keep the nuances of how the spec has been written and hadn't been influenced by the other PDF grammars, then the Required field might have been alternatively expressed as multi-valued: Required, Optional, Prohibited, Conditional, ...

**Comment by petervwyatt** [comment]
```
fn:IsRequired(fn:Not(fn:Contains(@Filter,JPXDecode) || (@ImageMask==true)))
```

which reads aloud as "Required except when Filter is not JPXDecode or ImageMask" which is correct I believe.
