### ISSUE TITLE
Views entry in RichMediaContent may contain 3DViewAddEntries

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/arlington-pdf-model#58]
**Views** entry in **RichMediaConent** references an array of 3D View dictionaries, which may contain additional entries introduced in PDF 2.0. So, this might require adding yet another type: **ArrayOf3DViewAddEntries** for this key. Currently the type of the **Views** entry is defined as **ArrayOf3DView**, which does not allow the use of additional entries in the **3DView** dictionaries.

**Comment by petervwyatt** [comment]
Well spotted. It is kind of annoying that 32K subclause 13.6.4 3D Views doesn't forward reference or make note of the fact that RichMedia can have additional entries for views so when you follow references back from elsewhere in RichMedia you neglect to notice this.

I also updated `RichMediaActivation` so that now RichMedia _only_ references `3DViewAddEntries` and never `3DView`. This also works from a versioning PoV.
