### ISSUE TITLE
issues with propagation of the data model

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/arlington-pdf-model#67]
The gcxml tool used to generate version specific tsv grammar files incorrectly supports:
```
fn:IsRequired(fn:SinceVersion(2.0,(fn:RectWidth(Rect)>0) || (fn:RectHeight(Rect)>0)))
```
This expression is replaced by `true` in the tsv file for version 2.0. The issue seem to be related with the code of

https://github.com/pdf-association/arlington-pdf-model/blob/80ada1cc457ff2c6d5ed0ccc2955b710a001f51e/gcxml/src/main/java/gcxml/TSVHandler.java#L596

**Comment by petervwyatt** [comment]
This and many other problems!
Rather than constantly trying to keep multiple implementations (C++, Java, Python) in sync, I propose to move to an ANTLR definition for be official definition of the Arlington predicate grammar: https://github.com/pdf-association/arlington-pdf-model/discussions/63. Do you like this idea or not?
