### ISSUE TITLE
PieceInfo and Info

### ISSUE THREAD

**Issue by faceless2** [pdf-association/arlington-pdf-model#69]
The document Info dictionary - `DocIInfo.tsv` - doesn't note that `ModDate` is "_Required if PieceInfo is present in the document catalog dictionary_". By extension, presumably the Info dictionary itself is required under the same condition, although this isn't listed as such in Table 15. Should an ISO32K2 errata fix this?

I'm raising it because https://github.com/veraPDF/veraPDF-corpus/blob/958e40f4445fb610112fb1a371e8a7c8d06bf277/ISO%2032000-2/veraPDF%20test%20suite%206-1-3-t04-fail-b.pdf tests for this condition, so @bdoubrov as a heads-up.

**Comment by petervwyatt** [comment]
Re ISO 32000-2:2020, Table 15 (Trailer) is where the statement you're looking for lives:

> As described in 14.3.3, "Document information dictionary", this method for specifying document metadata has been deprecated in PDF 2.0 and should therefore only be used to encode information that is stated as required elsewhere in this document.

> NOTE 1 The **ModDate** key within the **Info** dictionary is required if Page-Piece dictionaries (see 14.5, "Page-piece dictionaries") are used.

I will add the additional predicate. Thanks!

PS. The title of clause 14.3.3, "Document information dictionary", is a bit misleading as these dictionaries are also used by Threads (see 12.4.3 Articles and Table 162). It would be better to call them just "Information dictionaries" and then contextualise them as "doc info" or "thread info" when they are used.

**Comment by petervwyatt** [comment]
Maybe NOTE 1 should also have appended: "... in the document catalog." (since it is not required if Page-piece dicts are used with pages or Form XObjects, as they have their own **LastModified** entries)?

**Comment by petervwyatt** [comment]
Proposed fix in both `FileTrailer` and `XRefStream`:

Required column for **Info** = `fn:IsRequired(fn:IsPresent(trailer::Catalog::PieceInfo))`

SpecialCase column for **Info** = `fn:Eval(fn:IsPresent(trailer::Catalog::PieceInfo,IsPresent(trailer::Catalog::PieceInfo::ModDate)))`

**Comment by MaximPlusov** [comment]
I have some suggestions about predicate `fn:Eval(fn:IsPresent(trailer::Catalog::PieceInfo,IsPresent(trailer::Catalog::PieceInfo::ModDate)))`
1.  The inner predicate `IsPresent` is missing prefix `fn:`
2. Should be `Info::ModDate` instead of `trailer::Catalog::PieceInfo::ModDate`
3. Perhaps this predicate should be replaced with the simpler one: `fn:IsRequired(fn:IsPresent(trailer::Catalog::PieceInfo))` in Required column for **ModDate** in DocInfo
4. PieceInfo appears in PDF1.4, so maybe predicates in Required and SpecialCase fields for Info/ModDate should be wrapped in predicate `fn:SinceVersion(1.4,...)`

**Comment by petervwyatt** [comment]
Very sorry for the typos! Definitely need to improve validation...

Re point 3: this would be incorrect as DocInfo is also used by `Thread.tsv` (Articles and Threads) 

Re point 4: yes, for the traditional FileTrailer, but since XRefStreams were introduced in PDF 1.4 all is good. Thanks for picking this up.

**Comment by bdoubrov** [comment]
For point 3, I guess the question is what are the requirements to the value of the **I** entry in a thread dictionary. 

The spec says: _The contents of this dictionary shall conform to the syntax for the document information dictionary (see 14.3.3, "Document information dictionary")._ It is not clear, whether this includes the "deprecated/required" conditions as well. If yes, then I'd say @MaximPlusov is correct.

**Comment by petervwyatt** [comment]
For point 3: "12.4.3 Articles" only states that the optional **I** key is a doc info dict and `DocInfo` ModDate and CreationDate keys are not marked as Deprecated in PDF 2.0, so that would all be allowed (no deprecation concerns anywhere).  Nowhere is it stated that the DocInfo dict has to be the _same object_ as in trailer/**Info** (and in fact is often not if threads/articles are added via an incremental update with their own DocInfo dicts, and then a subsequent incremental update is done). So the requirement for a trailer/**Info** because of **PieceInfo** being present is entirely independent of DocInfo utilized by any Threads/Articles.

**Comment by petervwyatt** [comment]
I believe this is resolved.
