### ISSUE TITLE
Inconsistency in the VisibilityExpressionArray type

### ISSUE THREAD

**Issue by prashantbarca** [pdf-association/arlington-pdf-model#8]
The type in the `OptContentMembership` tsv file shows that the field `VE` is of type `array` and has a link `VisibilityExpressionArray`. 

When you look at the tsv file corresponding to the type `VisibilityExpressionArray`, on lines 3 and 4 they hold links back to `VisibilityExpressionArray`. However, the type specified here is `dictionary`. Should we be changing the type here to `dictionary;array` and the corresponding link to `[fn:SinceVersion(1.6,OptContentGroup)];[fn:SinceVersion(1.6,VisibilityExpressionArray)]`?

**Comment by petervwyatt** [comment]
Agreed. `VisibilityExpressionArray.tsv` is incorrect.

But the Type field needs to be `array;dictionary` as it needs to be alphabetical order :-) so the Link then becomes `[VisibilityExpressionArray];[OptContentGroup]`. The predicate for versions is also redundant here since the SinceVersion field is the same PDF version.

**Comment by petervwyatt** [comment]
And I will look into validating if the TestGrammar C++ PoC app can detect and report if a dictionary has purely integer key names (Key field) to highlight this specific error. AFAIK ISO 32000-2:2020 never defines this.

**Comment by petervwyatt** [comment]
Fixed in latest commit
